"""Deterministic imperfection engine: the observed state derived from truth.

The observed state is a deliberately-imperfect view of the truth graph, produced
by a *separate* transformation that reads the truth graph and applies a curated
taxonomy of defects, writing to ``generated/observed/``. It never mutates the
truth graph and never depends on any catalogue tool — it consumes the truth
graph in memory, exactly as the estate does. Every injected defect is recorded
explicitly, with before/after values and machine-readable expected findings and
remediations, so a future governance agent can be scored against known truth.

Generation is seeded and deterministic: the same config, truth seed, defect
seed, and profile produce byte-identical output. See ``docs/observed-state.md``
and ADR 0003.
"""

from __future__ import annotations

from dataswamp_biosystems.observed.defects import (
    DEFECTS,
    REQUIRED_CONTRACT_STATES,
    RULE_CONTRACTS,
    DefectDef,
    RuleContract,
    contract_coverage,
    defects_in_order,
    registry_rows,
    validate_registry,
)
from dataswamp_biosystems.observed.difficulty import (
    DIFFICULTY_BY_SCOPE,
    DIFFICULTY_MODEL_VERSION,
    DIFFICULTY_ORDER,
    RULE_DIFFICULTIES,
    RULE_REASONING_SCOPES,
    SCOPE_ORDER,
    Difficulty,
    DifficultySelection,
    ReasoningScope,
    UnavailableDifficultyError,
    UnknownRuleDifficultyError,
    classification_problems,
    difficulty_for,
    reasoning_scope_for,
    resolve_selection,
    rules_at,
    rules_by_difficulty,
    selectable_rules,
)
from dataswamp_biosystems.observed.engine import (
    ADVERSARIAL_MIN_SCHEMA_VERSION,
    OBSERVED_GENERATOR_VERSION,
    OBSERVED_SCHEMA_VERSION,
    SUPPORTED_OBSERVED_SCHEMA_VERSIONS,
    ObservedResult,
    generate_observed,
)
from dataswamp_biosystems.observed.entities import (
    NO_REMEDIATION_ACTION,
    ApprovalEvidence,
    ApprovalPolicy,
    ApproverRole,
    Category,
    ControlReason,
    ControlRecord,
    DefectInstance,
    ExpectedFinding,
    ExpectedRemediation,
    MutationRecord,
    NonRemediableReason,
    ObservedMeta,
    RemediationAvailability,
    RuleScopeRecord,
    Severity,
)
from dataswamp_biosystems.observed.errors import (
    ObservedConfigError,
    ObservedError,
    ObservedIssue,
    ObservedIssueKind,
    ObservedValidationError,
)
from dataswamp_biosystems.observed.inject import (
    InjectionReport,
    TruthImmutabilityError,
    compute_truth_checksums,
    ensure_output_outside_truth,
    inject_defects,
    load_truth_from_disk,
    resolve_truth_dir,
)
from dataswamp_biosystems.observed.profiles import (
    ObservedProfile,
    profile_spec,
    profile_specs,
)
from dataswamp_biosystems.observed.scenarios import (
    CASE_TYPE_ORDER,
    NEAR_MISS_DEFS,
    NEAR_MISS_VALIDITY_CHECKS,
    REQUIRED_CASE_TYPES,
    SCENARIO_CLASSES,
    SCENARIO_MODEL_VERSION,
    CaseType,
    ExpectedDetection,
    ExpectedRemediationBehaviour,
    ScenarioCase,
    ScenarioClass,
    ScenarioPolarity,
    ScenarioTransformation,
    ScenarioUnavailableError,
    plan_scenarios,
    scenario_coverage,
)
from dataswamp_biosystems.observed.validate import (
    read_observed_difficulty,
    read_observed_meta,
    validate_observed,
)
from dataswamp_biosystems.observed.writer import (
    CONTROLS_NAME,
    RULE_SCOPE_NAME,
    SCENARIO_TRANSFORMATIONS_NAME,
    SCENARIOS_NAME,
    write_observed,
)

__all__ = [
    "DEFECTS",
    "DIFFICULTY_BY_SCOPE",
    "DIFFICULTY_MODEL_VERSION",
    "DIFFICULTY_ORDER",
    "RULE_DIFFICULTIES",
    "RULE_REASONING_SCOPES",
    "SCOPE_ORDER",
    "Difficulty",
    "DifficultySelection",
    "ReasoningScope",
    "UnavailableDifficultyError",
    "UnknownRuleDifficultyError",
    "classification_problems",
    "difficulty_for",
    "reasoning_scope_for",
    "resolve_selection",
    "rules_at",
    "rules_by_difficulty",
    "selectable_rules",
    "DefectDef",
    "RuleContract",
    "RULE_CONTRACTS",
    "REQUIRED_CONTRACT_STATES",
    "contract_coverage",
    "defects_in_order",
    "registry_rows",
    "validate_registry",
    "inject_defects",
    "InjectionReport",
    "TruthImmutabilityError",
    "compute_truth_checksums",
    "ensure_output_outside_truth",
    "load_truth_from_disk",
    "resolve_truth_dir",
    "Category",
    "Severity",
    "RemediationAvailability",
    "ApprovalPolicy",
    "ApproverRole",
    "ApprovalEvidence",
    "NonRemediableReason",
    "NO_REMEDIATION_ACTION",
    "ControlReason",
    "ControlRecord",
    "RuleScopeRecord",
    "CONTROLS_NAME",
    "RULE_SCOPE_NAME",
    "SCENARIOS_NAME",
    "SCENARIO_TRANSFORMATIONS_NAME",
    "CASE_TYPE_ORDER",
    "NEAR_MISS_DEFS",
    "NEAR_MISS_VALIDITY_CHECKS",
    "REQUIRED_CASE_TYPES",
    "SCENARIO_CLASSES",
    "SCENARIO_MODEL_VERSION",
    "CaseType",
    "ExpectedDetection",
    "ExpectedRemediationBehaviour",
    "ScenarioCase",
    "ScenarioClass",
    "ScenarioPolarity",
    "ScenarioTransformation",
    "ScenarioUnavailableError",
    "plan_scenarios",
    "scenario_coverage",
    "DefectInstance",
    "MutationRecord",
    "ExpectedFinding",
    "ExpectedRemediation",
    "ObservedMeta",
    "ObservedProfile",
    "profile_spec",
    "profile_specs",
    "ADVERSARIAL_MIN_SCHEMA_VERSION",
    "OBSERVED_GENERATOR_VERSION",
    "OBSERVED_SCHEMA_VERSION",
    "SUPPORTED_OBSERVED_SCHEMA_VERSIONS",
    "ObservedResult",
    "generate_observed",
    "read_observed_difficulty",
    "read_observed_meta",
    "validate_observed",
    "write_observed",
    "ObservedError",
    "ObservedConfigError",
    "ObservedValidationError",
    "ObservedIssue",
    "ObservedIssueKind",
]
