"""Validate a generated observed estate against its bytes and its bookkeeping.

``validate-observed`` regenerates the observed state from the recorded profile
and defect seed and confirms it is byte-identical to what is on disk (a
determinism/integrity tripwire), then checks the ledgers hold together:
structural completeness and referential integrity across the four streams,
fidelity of every mutation's ``before`` to the truth graph, and the absence of
contradictory or control-touching mutations.

It deliberately does **not** enforce the truth-graph invariants on the observed
graph — the observed graph is *supposed* to be broken. It validates the
bookkeeping, not the correctness of the estate.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from dataswamp_biosystems.company.config import CanonicalConfig
from dataswamp_biosystems.observed.defects import DEFECTS
from dataswamp_biosystems.observed.engine import ObservedResult, generate_observed
from dataswamp_biosystems.observed.entities import ChangeOp, MutationRecord
from dataswamp_biosystems.observed.errors import (
    ObservedConfigError,
    ObservedIssueCollector,
    ObservedIssueKind,
)
from dataswamp_biosystems.observed.index import GraphIndex
from dataswamp_biosystems.observed.profiles import ObservedProfile
from dataswamp_biosystems.observed.writer import (
    PROFILE_SUMMARY_NAME,
    SUMMARY_MD_NAME,
    observed_bytes,
)
from dataswamp_biosystems.truth.graph import TruthGraph


def read_observed_meta(observed_dir: Path) -> dict[str, Any]:
    """Read the ``meta`` block from ``profile-summary.json``."""
    path = observed_dir / PROFILE_SUMMARY_NAME
    if not path.exists():
        raise ObservedConfigError(f"no profile summary at {path}")
    try:
        summary = json.loads(path.read_text(encoding="utf-8"))
        meta = summary["meta"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        raise ObservedConfigError(f"could not read observed summary {path}: {exc}") from exc
    if not isinstance(meta, dict):
        raise ObservedConfigError(f"malformed meta block in {path}")
    return meta


def validate_observed(observed_dir: Path, graph: TruthGraph, config: CanonicalConfig) -> None:
    """Validate the observed estate under ``observed_dir`` against ``graph`` and disk.

    ``graph`` must be the truth graph the estate was derived from (same seed).
    Raises :class:`ObservedValidationError` on any problem.
    """
    observed_dir = Path(observed_dir)
    issues = ObservedIssueCollector()

    meta = read_observed_meta(observed_dir)
    profile = ObservedProfile(str(meta["profile"]))
    defect_seed = int(str(meta["defect_seed"]))
    truth_seed = int(str(meta["truth_seed"]))
    if graph.meta.seed != truth_seed:
        issues.add(
            ObservedIssueKind.CONSISTENCY,
            f"truth graph seed {graph.meta.seed} does not match observed truth_seed {truth_seed}",
        )

    result = generate_observed(graph, config, profile, defect_seed)

    # Determinism/integrity tripwire: regenerated bytes must match disk.
    for name, data in observed_bytes(result).items():
        on_disk = (observed_dir / name).read_bytes() if (observed_dir / name).exists() else b""
        if on_disk != data:
            issues.add(
                ObservedIssueKind.CONSISTENCY,
                f"on-disk {name} differs from a freshly regenerated file (drift)",
                entity_kind=name,
            )
    md_path = observed_dir / SUMMARY_MD_NAME
    if not md_path.exists():
        issues.add(ObservedIssueKind.CONSISTENCY, f"missing {SUMMARY_MD_NAME}")

    index = GraphIndex(graph, config)
    _check_structural(result, issues)
    _check_fidelity(result, index, issues)
    _check_contamination(result, issues)

    issues.raise_if_any()


def _check_structural(result: ObservedResult, issues: ObservedIssueCollector) -> None:
    instance_ids = {i.id for i in result.instances}
    finding_ids = {f.id for f in result.findings}
    mutation_ids = {m.id for m in result.mutations}
    remediation_ids = {r.id for r in result.remediations}

    _check_unique([i.id for i in result.instances], "instance", issues)
    _check_unique([m.id for m in result.mutations], "mutation", issues)
    _check_unique([f.id for f in result.findings], "finding", issues)
    _check_unique([r.id for r in result.remediations], "remediation", issues)

    muts_by_instance: dict[str, int] = {}
    for mutation in result.mutations:
        muts_by_instance[mutation.instance_id] = muts_by_instance.get(mutation.instance_id, 0) + 1
        if mutation.instance_id not in instance_ids:
            issues.add(
                ObservedIssueKind.UNRESOLVED_REFERENCE,
                f"mutation references unknown instance {mutation.instance_id!r}",
                entity_kind="mutation",
                entity_id=mutation.id,
            )
        if mutation.rule_id not in DEFECTS:
            issues.add(
                ObservedIssueKind.UNKNOWN_RULE,
                f"mutation references unknown rule {mutation.rule_id!r}",
                entity_kind="mutation",
                entity_id=mutation.id,
            )

    findings_by_instance: dict[str, int] = {}
    for finding in result.findings:
        findings_by_instance[finding.instance_id] = (
            findings_by_instance.get(finding.instance_id, 0) + 1
        )
        if finding.instance_id not in instance_ids:
            issues.add(
                ObservedIssueKind.UNRESOLVED_REFERENCE,
                f"finding references unknown instance {finding.instance_id!r}",
                entity_kind="finding",
                entity_id=finding.id,
            )
        if finding.remediation_id not in remediation_ids:
            issues.add(
                ObservedIssueKind.UNRESOLVED_REFERENCE,
                f"finding references unknown remediation {finding.remediation_id!r}",
                entity_kind="finding",
                entity_id=finding.id,
            )

    for remediation in result.remediations:
        if remediation.instance_id not in instance_ids:
            issues.add(
                ObservedIssueKind.UNRESOLVED_REFERENCE,
                f"remediation references unknown instance {remediation.instance_id!r}",
                entity_kind="remediation",
                entity_id=remediation.id,
            )
        if remediation.finding_id not in finding_ids:
            issues.add(
                ObservedIssueKind.UNRESOLVED_REFERENCE,
                f"remediation references unknown finding {remediation.finding_id!r}",
                entity_kind="remediation",
                entity_id=remediation.id,
            )

    remediations_by_instance: dict[str, int] = {}
    for remediation in result.remediations:
        remediations_by_instance[remediation.instance_id] = (
            remediations_by_instance.get(remediation.instance_id, 0) + 1
        )

    for instance in result.instances:
        if muts_by_instance.get(instance.id, 0) < 1:
            issues.add(
                ObservedIssueKind.LEDGER,
                "instance has no mutation records",
                entity_kind="instance",
                entity_id=instance.id,
            )
        if findings_by_instance.get(instance.id, 0) != 1:
            issues.add(
                ObservedIssueKind.LEDGER,
                "instance must have exactly one finding",
                entity_kind="instance",
                entity_id=instance.id,
            )
        if remediations_by_instance.get(instance.id, 0) < 1:
            issues.add(
                ObservedIssueKind.LEDGER,
                "instance has no remediation records",
                entity_kind="instance",
                entity_id=instance.id,
            )
        if instance.rule_id not in DEFECTS:
            issues.add(
                ObservedIssueKind.UNKNOWN_RULE,
                f"instance references unknown rule {instance.rule_id!r}",
                entity_kind="instance",
                entity_id=instance.id,
            )
        for mutation_id in instance.mutation_ids:
            if mutation_id not in mutation_ids:
                issues.add(
                    ObservedIssueKind.UNRESOLVED_REFERENCE,
                    f"instance references unknown mutation {mutation_id!r}",
                    entity_kind="instance",
                    entity_id=instance.id,
                )
        if instance.finding_id not in finding_ids:
            issues.add(
                ObservedIssueKind.UNRESOLVED_REFERENCE,
                f"instance references unknown finding {instance.finding_id!r}",
                entity_kind="instance",
                entity_id=instance.id,
            )
        for remediation_id in instance.remediation_ids:
            if remediation_id not in remediation_ids:
                issues.add(
                    ObservedIssueKind.UNRESOLVED_REFERENCE,
                    f"instance references unknown remediation {remediation_id!r}",
                    entity_kind="instance",
                    entity_id=instance.id,
                )


def _check_unique(values: list[str], kind: str, issues: ObservedIssueCollector) -> None:
    seen: set[str] = set()
    for value in values:
        if value in seen:
            issues.add(
                ObservedIssueKind.DUPLICATE_ID,
                f"duplicate {kind} id {value!r}",
                entity_kind=kind,
                entity_id=value,
            )
        seen.add(value)


def _truth_value(index: GraphIndex, mutation: MutationRecord) -> Any:
    record = index.truth_record(mutation.shard, mutation.entity_id)
    if record is None:
        return None
    if mutation.operation is ChangeOp.DELETE_RECORD:
        return record
    return record.get(mutation.field)


def _check_fidelity(
    result: ObservedResult, index: GraphIndex, issues: ObservedIssueCollector
) -> None:
    observed = {
        shard: {r["id"]: r for r in records}
        for shard, records in result.observed_graph.items()
        if shard != "meta"
    }
    for mutation in result.mutations:
        if mutation.operation is ChangeOp.ADD_RECORD:
            continue
        truth_value = _truth_value(index, mutation)
        if mutation.before != truth_value:
            issues.add(
                ObservedIssueKind.FIDELITY,
                "mutation before-value does not match the truth graph",
                entity_kind="mutation",
                entity_id=mutation.id,
                field=mutation.field,
            )
        if mutation.operation in (ChangeOp.SET, ChangeOp.SET_LIST):
            record = observed.get(mutation.shard, {}).get(mutation.entity_id)
            if record is None or record.get(mutation.field) != mutation.after:
                issues.add(
                    ObservedIssueKind.FIDELITY,
                    "mutation after-value is not present in the observed graph",
                    entity_kind="mutation",
                    entity_id=mutation.id,
                    field=mutation.field,
                )


def _check_contamination(result: ObservedResult, issues: ObservedIssueCollector) -> None:
    # No two SET mutations may share a (shard, entity, field) path.
    set_paths: set[tuple[str, str, str]] = set()
    for mutation in result.mutations:
        if mutation.operation in (ChangeOp.SET, ChangeOp.SET_LIST):
            key = (mutation.shard, mutation.entity_id, mutation.field)
            if key in set_paths:
                issues.add(
                    ObservedIssueKind.CONTAMINATION,
                    f"two mutations write the same path {key}",
                    entity_kind="mutation",
                    entity_id=mutation.id,
                    field=mutation.field,
                )
            set_paths.add(key)

    # No entity may carry two mutually incompatible rules.
    rules_by_entity: dict[str, set[str]] = {}
    for instance in result.instances:
        rules_by_entity.setdefault(instance.entity_id, set()).add(instance.rule_id)
    for entity_id, rules in rules_by_entity.items():
        for rule_id in rules:
            incompatible = set(DEFECTS[rule_id].incompatibilities) & rules
            if incompatible:
                issues.add(
                    ObservedIssueKind.INCOMPATIBILITY,
                    f"entity carries incompatible rules {rule_id!r} and {sorted(incompatible)}",
                    entity_kind="instance",
                    entity_id=entity_id,
                )


__all__ = ["read_observed_meta", "validate_observed"]
