"""Environment and scenario provenance for generated benchmark output.

Every generated output directory carries one shared ``provenance.json``
recording what produced it: the DataSwamp version, the Python version and
platform, the resolved versions of the direct dependencies, a fingerprint of
those versions, and the scenario identity (generator/schema versions, seeds and
profile). One object per output directory, referenced implicitly by everything
beside it, so no large dependency list is copied into individual records.

Provenance deliberately carries **no wall-clock value**: it is a pure function
of the environment and the scenario, so two runs in the same environment write
identical bytes. It is nevertheless *excluded* from the canonical golden digests
(see :mod:`tests.test_golden`), because it is precisely the artefact that is
expected to differ between a locked and a lowest-direct environment. The
determinism claim is about the generated benchmark data; provenance is the
evidence needed to interpret that claim.

The environment fingerprint covers the **direct dependency versions only**, not
the Python version: Python 3.12 and 3.13 are verified to produce byte-identical
output from the same dependency set, so the dependency set is what determines
the bytes.
"""

from __future__ import annotations

import platform
import sys
from importlib import metadata
from typing import Any

from dataswamp_biosystems import __version__
from dataswamp_biosystems.truth import serialize

PROVENANCE_NAME = "provenance.json"
PROVENANCE_SCHEMA_VERSION = 1

# The distributions declared in ``[project].dependencies``. Their resolved
# versions determine the generated bytes, so they are the fingerprint's input.
DIRECT_DEPENDENCIES: tuple[str, ...] = (
    "anndata",
    "numpy",
    "pillow",
    "pyarrow",
    "pydantic",
    "pyyaml",
    "tifffile",
    "typer",
)

UNKNOWN_VERSION = "unknown"


def direct_dependency_versions() -> dict[str, str]:
    """Return ``{distribution: version}`` for every direct dependency, name-sorted."""
    versions: dict[str, str] = {}
    for name in sorted(DIRECT_DEPENDENCIES):
        try:
            versions[name] = metadata.version(name)
        except metadata.PackageNotFoundError:  # pragma: no cover - defensive
            versions[name] = UNKNOWN_VERSION
    return versions


def environment_fingerprint(versions: dict[str, str] | None = None) -> str:
    """Return a SHA-256 fingerprint of the direct dependency versions.

    Two environments sharing a fingerprint are expected to produce byte-identical
    benchmark output, including the binary scientific files. Environments with
    different fingerprints still agree on the metadata layers (truth graph and
    observed-state ledgers) — see ``docs/reproducibility.md``.
    """
    resolved = direct_dependency_versions() if versions is None else versions
    return serialize.digest(serialize.canonical_json(resolved).encode("utf-8"))


def python_identity() -> dict[str, str]:
    """Return the Python identity fields, without patch-level or build noise."""
    return {
        "version": f"{sys.version_info.major}.{sys.version_info.minor}",
        "implementation": platform.python_implementation(),
    }


def platform_identity() -> dict[str, str]:
    """Return the coarse platform identity (no hostname, no release detail)."""
    return {"system": platform.system(), "machine": platform.machine()}


def build_provenance(
    *,
    layer: str,
    generator_version: str,
    schema_version: int,
    scenario: dict[str, Any],
) -> dict[str, Any]:
    """Build the provenance payload for one generated output directory.

    ``layer`` is ``truth``, ``estate`` or ``observed``; ``scenario`` carries the
    seeds, profile and any truth linkage that identifies what was generated.
    """
    versions = direct_dependency_versions()
    return {
        "provenance_schema_version": PROVENANCE_SCHEMA_VERSION,
        "dataswamp_version": __version__,
        "layer": layer,
        "generator_version": generator_version,
        "schema_version": schema_version,
        "python": python_identity(),
        "platform": platform_identity(),
        "direct_dependencies": versions,
        "environment_fingerprint": environment_fingerprint(versions),
        "scenario": dict(sorted(scenario.items())),
        "synthetic": True,
    }


def provenance_bytes(
    *,
    layer: str,
    generator_version: str,
    schema_version: int,
    scenario: dict[str, Any],
) -> bytes:
    """Return the canonical JSON bytes of a provenance payload."""
    return serialize.manifest_bytes(
        build_provenance(
            layer=layer,
            generator_version=generator_version,
            schema_version=schema_version,
            scenario=scenario,
        )
    )


__all__ = [
    "PROVENANCE_NAME",
    "PROVENANCE_SCHEMA_VERSION",
    "DIRECT_DEPENDENCIES",
    "UNKNOWN_VERSION",
    "direct_dependency_versions",
    "environment_fingerprint",
    "python_identity",
    "platform_identity",
    "build_provenance",
    "provenance_bytes",
]
