"""What the three reference baselines actually score at each difficulty tier.

The expected numbers below are written out by hand from a measured run, not
regenerated by the test, so this file cannot launder a changed agent into a green
suite: a behaviour change has to be re-read and re-typed by whoever makes it.

Nothing here tunes an agent. The baselines are the ones published in
``docs/baselines.md``, run unmodified against a tier-restricted benchmark, and
the results are reported as measured — including the one that is *worse* at
bronze-and-silver than the naive agent is at gold, and the rule-based agent's
zero at gold. Difficulty is not assumed to be monotonic in agent skill, and the
suite must not quietly start assuming it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from dataswamp_biosystems.baselines import (
    ADVERSARIAL_ONLY_INPUT_FILES,
    ALWAYS_PRESENT_FORBIDDEN_FILES,
    BASELINE_NAMES,
    ObservedInput,
    get_baseline,
    render_predictions,
    run_baseline,
)
from dataswamp_biosystems.canonical import CANONICAL_DEFECT_SEED, CANONICAL_TRUTH_SEED
from dataswamp_biosystems.company import load_config
from dataswamp_biosystems.evaluation import (
    evaluate,
    load_ground_truth,
    parse_predictions,
    prediction_digest,
)
from dataswamp_biosystems.observed.difficulty import Difficulty, difficulty_for
from dataswamp_biosystems.observed.engine import generate_observed
from dataswamp_biosystems.observed.profiles import ObservedProfile
from dataswamp_biosystems.observed.writer import write_observed
from dataswamp_biosystems.truth import generate_truth_graph, load_generation_plan

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = REPO_ROOT / "config"

TIERS = ("bronze", "silver", "gold")

# Measured against the canonical scenario (demo profile, truth seed
# CANONICAL_TRUTH_SEED, defect seed CANONICAL_DEFECT_SEED) with the tier filter
# applied at generation. Keys: tp, fp, fn, tn.
EXPECTED: dict[str, dict[str, tuple[int, int, int, int]]] = {
    "bronze": {
        "null": (0, 0, 63, 2012),
        "naive-metadata": (53, 0, 10, 2012),
        "rule-based": (61, 0, 2, 2012),
    },
    "silver": {
        "null": (0, 0, 76, 2798),
        "naive-metadata": (0, 0, 76, 2798),
        "rule-based": (45, 0, 31, 2798),
    },
    "gold": {
        "null": (0, 0, 62, 2110),
        "naive-metadata": (16, 10, 46, 2100),
        "rule-based": (0, 0, 62, 2110),
    },
}

# Defects injected per tier under the canonical scenario, and the rule count each
# tier scopes. Pinned because a change here moves every score above.
EXPECTED_SCENARIO = {
    "bronze": {"defects": 63, "rules": 13},
    "silver": {"defects": 76, "rules": 15},
    "gold": {"defects": 62, "rules": 13},
}


@pytest.fixture(scope="module")
def tier_observed_dirs(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    """One written observed state per tier, generated once for this module."""
    config = load_config(CONFIG_DIR)
    plan = load_generation_plan(CONFIG_DIR)
    graph = generate_truth_graph(config, plan, CANONICAL_TRUTH_SEED)
    root = tmp_path_factory.mktemp("tier-observed")

    directories: dict[str, Path] = {}
    for tier in TIERS:
        result = generate_observed(
            graph, config, ObservedProfile.DEMO, CANONICAL_DEFECT_SEED, Difficulty(tier)
        )
        target = root / tier
        write_observed(result, target)
        directories[tier] = target
    return directories


def _score(observed_dir: Path, agent_name: str) -> Any:
    truth = load_ground_truth(observed_dir)
    run = run_baseline(get_baseline(agent_name), ObservedInput.load(observed_dir))
    raw = render_predictions(run.predictions).encode("utf-8")
    submitted = parse_predictions(
        raw.decode("utf-8"),
        known_entities=truth.known_entities,
        known_rules=truth.rule_ids,
    )
    return evaluate(truth, submitted, prediction_digest=prediction_digest(raw))


@pytest.fixture(scope="module")
def tier_results(tier_observed_dirs: dict[str, Path]) -> dict[str, dict[str, Any]]:
    return {
        tier: {name: _score(directory, name) for name in BASELINE_NAMES}
        for tier, directory in tier_observed_dirs.items()
    }


def test_every_tier_benchmark_is_the_scenario_it_claims_to_be(
    tier_observed_dirs: dict[str, Path],
) -> None:
    for tier, expected in EXPECTED_SCENARIO.items():
        truth = load_ground_truth(tier_observed_dirs[tier])
        assert len(truth.findings) == expected["defects"], tier
        assert len(truth.scopes) == expected["rules"], tier
        assert all(difficulty_for(scope.id).value == tier for scope in truth.scopes)


@pytest.mark.parametrize("tier", TIERS)
@pytest.mark.parametrize("agent_name", ["null", "naive-metadata", "rule-based"])
def test_measured_tier_scores(
    tier_results: dict[str, dict[str, Any]], tier: str, agent_name: str
) -> None:
    """The published per-tier confusion matrix, pinned cell by cell.

    A failure here means a baseline's tier behaviour changed. That is a reviewed
    edit: re-measure, update ``docs/baselines.md`` and the table above together.
    """
    counts = tier_results[tier][agent_name].summary["findings"]["overall_micro"]["counts"]
    tp, fp, fn, tn = EXPECTED[tier][agent_name]
    assert (counts["tp"], counts["fp"], counts["fn"], counts["tn"]) == (tp, fp, fn, tn)


@pytest.mark.parametrize("tier", TIERS)
def test_no_baseline_ever_flags_a_reserved_control(
    tier_results: dict[str, dict[str, Any]], tier: str
) -> None:
    """The control partition holds at every tier, not just the mixed default."""
    for agent_name in BASELINE_NAMES:
        summary = tier_results[tier][agent_name].summary
        assert summary["reserved_controls"]["false_positives"] == 0
        assert summary["remediation"]["counts"]["unsafe_actions"] == 0


@pytest.mark.parametrize("tier", TIERS)
def test_a_tier_report_attributes_everything_to_that_one_tier(
    tier_results: dict[str, dict[str, Any]], tier: str
) -> None:
    """A bronze benchmark scores bronze pairs and reports the other tiers empty."""
    for agent_name in BASELINE_NAMES:
        by_difficulty = tier_results[tier][agent_name].summary["findings"]["by_difficulty"]
        assert by_difficulty[tier]["counts"]["total"] > 0
        for other in set(TIERS) - {tier}:
            assert by_difficulty[other]["counts"]["total"] == 0
            # Never zero — an unmeasured tier is not a perfect one.
            assert by_difficulty[other]["metrics"]["specificity"]["value"] is None


@pytest.mark.parametrize("tier", TIERS)
def test_tier_predictions_are_deterministic(tier_observed_dirs: dict[str, Path], tier: str) -> None:
    for agent_name in BASELINE_NAMES:
        agent = get_baseline(agent_name)
        observed = ObservedInput.load(tier_observed_dirs[tier])
        first = render_predictions(run_baseline(agent, observed).predictions)
        second = render_predictions(run_baseline(agent, observed).predictions)
        assert first == second


@pytest.mark.parametrize("tier", TIERS)
def test_tier_benchmarks_expose_no_privileged_input(
    tier_observed_dirs: dict[str, Path], tier: str
) -> None:
    """The anti-leakage boundary is a property of the input loader, not the mix.

    A tier-restricted observed state contains exactly the same forbidden files as
    the mixed one, and a baseline must still be unable to reach any of them. The
    two adversarial-only ledgers are excluded because an ordinary tier does not
    emit them at all — that absence is itself asserted below.
    """
    observed_dir = tier_observed_dirs[tier]
    for name in ALWAYS_PRESENT_FORBIDDEN_FILES:
        assert (observed_dir / name).exists(), f"{name} missing — the test proves nothing"
    for name in ADVERSARIAL_ONLY_INPUT_FILES:
        assert not (observed_dir / name).exists(), (
            f"{name} was emitted by an ordinary tier; scenario ledgers belong to "
            "adversarial runs alone"
        )
    observed = ObservedInput.load(observed_dir)
    assert not hasattr(observed, "findings")
    assert not hasattr(observed, "rule_scopes")
